print("WebPhising:www.facebookol.com")
print("WebPhising:www.localhost:8080.com")
print("Email:anonyusdarker0@protonmail.com")
print("MyFB:https://www.facebook.com/alonkreker.hacker/")
print("MyYt:https://www.youtube.com/channel/UCWr7FLzT4LDkusCVIB61GeQ/videos")
